- name: Install required packages
  action: apt pkg={{item}} state=installed
  with_items:
    - curl
    - unzip
    - vim
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - systemd
- name: Create nomad config dir
  action: file path=/etc/{{item}} state=directory mode=0755 owner=bin group=bin
  with_items:
    - nomad.d
    - consul.d
- name: Install nomad from local zip file
  unarchive:
    src: roles/consul/files/nomad.zip
    dest: /usr/bin
- name: Install consul from local zip file
  unarchive:
    src: roles/consul/files/consul.zip
    dest: /usr/bin
- name: Instal consul config file
  template:
    src: roles/consul/files/consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: bin
    group: bin
    mode: 644    
- name: Enable consul service
  systemd: enabled=yes name=consul.service
- name: Start consul service
  systemd: state=started name=consul

