---
- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
  - name: Configure host/domain name
    hostname: 
      name: "{{ inventory_hostname }}"

  - name: Add entries to hosts file
    action: lineinfile path=/etc/hosts line={{item}} owner=root group=root mode=644
    with_items:
      - "192.168.110.10 subhost1"
      - "192.168.110.11 exec1"
      - "192.168.110.12 exec2"
  roles:
    - common
    - consul

- hosts: submit
  remote_user: vagrant
  become: yes
  roles:
    - nismaster
  tasks:
  - name: Provision nomad config file
    template:
      src: server.hcl.j2
      dest: /etc/nomad.d/server.hcl
      owner: bin
      group: bin
      mode: 644    

- hosts: ~submit
  remote_user: vagrant
  become: yes
  tasks:
    - name: Bogus
      lineinfile:
        path: /etc/hosts 
        line: "# this is just a comment"
        owner: root 
        group: root 
        mode: 644

- hosts: exec
  remote_user: vagrant
  become: yes
  tasks:
  - name: Provision nomad config file
    template:
      src: client.hcl.j2
      dest: /etc/nomad.d/client.hcl
      owner: bin
      group: bin
      mode: 644    

