# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"
  config.vm.network :forwarded_port, guest: 80, host: 4567

  config.vm.provision "ansible" do |ansible|
#    ansible.groups = {
#      "submit" => ["subhost1"],
#      "exec" => ["exec[1:2]"],
#      "all:vars" => {
#        "consul_server" => "subhost1",
#        "consul_server_flag" => ""
#      }
#    }
    ansible.playbook = "playbook.yml"
#    ansible.host_vars = {
#      "subhost1" => {
#        "private_ip" => "192.168.110.10",
#        "consul_server_flag" => "-server -bootstrap-expect=1",
#        "nis_server" => "True"
#      },
#      "exec1" => { "private_ip" => "192.168.110.11" },
#      "exec2" => { "private_ip" => "192.168.110.12" }
#    }
  end
end
